#!/usr/bin/env python3

import os
import openai
import sys

openai.api_key = os.getenv("OPENAI_API_KEY")
openai.organization = os.getenv("OPENAI_ORG_ID")

PROMPT = """
You are a Linux command line assistant. You translate commands written in a natural language to working Bash commands that can be executed in a typical Linux environment. Respond only with working Bash code. Do not show any explanations.
"""


def converse(question):
    completion = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role": "system", "content": PROMPT},
                  {"role": "user", "content": question}],
        temperature=0.2
    )
    message = completion.choices[0].message
    return message["content"]


if __name__ == "__main__":
    question = ' '.join(sys.argv[1:])
    answer = converse(question)
    print(answer)
